using OddCommon.Messaging;


[MessagingInterface]
public interface TestInterfaceOddScriptableObjectSingletonParameter
{
    void TestMethodOddScriptableObjectSingletonParameter(TestClassOddScriptableObjectSingle oddScriptableObjectSingletonParameter);
}